### ISSUE TITLE
Make a new component for detailed information card and add the ability to scroll

### ISSUE THREAD

**Issue by srathi7** [JIB-8352/chatham_smart_map#112]
Expect to receive an array of geoJSONs, x-axis points should be the timelapse points but plot all the data points that we pull from API

**Comment by PC98** [comment]
Can use one of these:
1. https://github.com/apertureless/vue-chartjs
2. https://github.com/ElemeFE/v-charts
3. https://github.com/ecomfe/vue-echarts

**Comment by PC98** [comment]
Include basic information from the hover popup
