### ISSUE TITLE
Inundation Layer Demo

### ISSUE THREAD

**Issue by rconklin6** [JIB-8352/chatham_smart_map#182]

**Comment by PC98** [comment]
HUTCHINSON ISLAND SENSOR

**Comment by rconklin6** [comment]
- look into "bounding boxes" and how they work
- look into getting navd88 reading (possibly just make a constant here for the demo)

**Comment by rconklin6** [comment]
- constants based on category of hurricane:
    - Cat1: 4-11
    - Cat2: 11-17
    - Cat3: 17-23
    - Cat4: 23-26
    - Cat5: 26-31
