### ISSUE TITLE
Add sensor GeoJSON data as a layer to the map

### ISSUE THREAD

**Issue by PC98** [JIB-8352/chatham_smart_map#59]
https://github.com/PC98/Junior_Design_Demo_App/blob/master/index.html#L130

**Comment by PC98** [comment]
https://github.com/phegman/vue-mapbox-gl

**Comment by monirakhan** [comment]
Things -> Datastreams link -> Observations -> Data should be found here

**Comment by monirakhan** [comment]
https://api.sealevelsensors.org/v1.0/Things
to
https://api.sealevelsensors.org/v1.0/Things(2)/Datastreams
to
https://api.sealevelsensors.org/v1.0/Datastreams(2)/Observations
in which the "results" is the meters of distance aka what we want
