### ISSUE TITLE
Implement functionality that closes card/unselects sensor once its clicked on

### ISSUE THREAD

**Issue by srathi7** [JIB-8352/chatham_smart_map#87]

**Comment by PC98** [comment]
1. sensor name should appear in search bar. when the X is clicked, sensor should be unselected - also perform necessary changes to the Console.
2. The same closing functionality can be achieved by clicking on a selected sensor.
3. Make sure this doesn't change the interaction when an unselected sensor is clicked given that another sensor is selected.
